# Generated by Django 3.2.4 on 2021-10-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_custombaseuser_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='roll_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='custombaseuser',
            name='user_type',
            field=models.CharField(choices=[('TC', 'Teacher'), ('ST', 'Student')], max_length=10),
        ),
    ]
