# Generated by Django 3.2.4 on 2021-10-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211001_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='custombaseuser',
            name='user_type',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=10),
        ),
    ]
