# Generated by Django 3.2.4 on 2021-10-05 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_teacherprofile_iscompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.year'),
        ),
    ]
