# Generated by Django 3.2.4 on 2021-10-05 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_studentprofile_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='users.department'),
        ),
    ]
