# Generated by Django 3.2.4 on 2021-10-07 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20211007_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='sid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
    ]
