# Generated by Django 3.2.4 on 2021-10-07 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_marks_sid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='sid',
            new_name='student_id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='marks',
        ),
        migrations.AddField(
            model_name='marks',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.subject'),
        ),
    ]
