# Generated by Django 3.2.4 on 2021-10-07 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20211007_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='student_id',
        ),
        migrations.AddField(
            model_name='subject',
            name='marks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.marks'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_id', to='users.subject'),
        ),
    ]
