# Generated by Django 3.2.4 on 2021-10-07 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20211007_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
    ]
