# Generated by Django 3.2.4 on 2021-10-07 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_subject_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='marks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.marks'),
        ),
    ]
