# Generated by Django 3.2.4 on 2021-10-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_subject_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(related_name='teacher', to='users.TeacherProfile'),
        ),
    ]
